#!/usr/bin/python3

import sys
import time


def factorize(number):
    for i in range(2, number):
        if number % i == 0:
            return f"{number}={i}*{number // i}"


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(1)

    fileName = sys.argv[1]

    startTime = time.time()

    with open(fileName, 'r') as theFile:
        for line in theFile:
            currentTime = time.time()
            diff = currentTime - startTime
            if diff > 5:
                print("\n----\nHehe\n----\n")
                break;
            number = int(line.strip())
            result = factorize(number)
            if result:
                print(diff)
                print(result)
    now = time.time() - startTime
    print(now)
